version: '3.8'
services:
  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "5001:5001"

  order_service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
    ports:
      - "5002:5002"