server:
  port: 8081

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:h2:mem:hoteldb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: mysupersecurekey1234567890abcdef

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.143